version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.16.2
    container_name: vault
    environment:
        VAULT_ADDR: http://127.0.0.1:8200
    ports:
        - "8200:8200"
    volumes:
        - ./vault-data:/vault/file:rw
        - ./vault.hcl:/vault/config/vault.hcl:rw
    cap_add:
        - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
